# Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: osi-github-workshop-k8manifest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    argo/module: k8Manifest
spec:
  project: default

  source:
    repoURL: https://github.com/rajmayank/OSI-GitOps-Workshop.git
    targetRevision: HEAD
    path: infrastructure/k8-manifests/

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 5
        maxDuration: 5m

  revisionHistoryLimit: 10